### ISSUE TITLE
newgrounds.com

### ISSUE THREAD

**Issue by CelloD** [apkcube/blockhostid#12]
User's profile still blocked
Ex : http://schtiffles.newgrounds.com/
But its seems impossible to add all user profile
Or there is any workaround?

**Comment by apkcube** [comment]
Can you tell me all the list subdomain who got blocked?

**Comment by apkcube** [comment]
Hmm, seems like that things is impossible to work with this project, i can't list all of that. :/

**Comment by apkcube** [comment]
But you can manually unblock the subdomain you want to access by adding ip before subdomain on hosts file.

Ex:
104.20.59.153 schtiffles.newgrounds.com

Use:
104.20.59.153 [subdomain]

**Comment by CelloD** [comment]
Okay thx :)
