### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by makingcat1** [apkcube/blockhostid#14]
bang tambahin steam dan kawan2 nya dong.
sama twitch.tv.
kalo sempat minta tutor nya, barangkali bisa bantu2 >_<

**Comment by makingcat1** [comment]
drop link tutor aja pls

**Comment by makingcat1** [comment]
sama mrpornx.com

**Comment by anonimuskai** [comment]
tolong tambahkan ini

185.2.83.141 i.nhentai.net
185.2.83.13 i.nhentai.net

**Comment by apkcube** [comment]
Steam sama Twitch saya lihat dari sini tidak diblokir, untuk Mrpornx telah saya kerjakan.

**Comment by apkcube** [comment]
Ok, bug diterima, akan saya tambahkan.

**Comment by apkcube** [comment]
Tapi untuk yang mrpornx.com silahkan akses pakai www tanpa pakai itu akan tidak bisa.
