### ISSUE TITLE
Tambah tutorial untuk pemasangan di OS selain Android dan Windows

### ISSUE THREAD

**Issue by novalkomik** [apkcube/blockhostid#17]
Sebaiknya tutorial pemasangan pada OS Linux dan MacOS disediakan, karena banyak yg ingin pakai di kedua OS itu namun ragu akan pemasangannya. thx

**Comment by apkcube** [comment]
Untuk linux dan mac sama-sama terletak di /etc/hosts, untuk cara mengeditnya pun sama, bisa replace atau add manual. Tapi sebelumnya bisa minta samplenya tidak, kirimkan filenya ke saya nanti saya cek ulang, jika ada perbedaan bisa saya republish untuk versi linux/mac-nya.

**Comment by apkcube** [comment]
Untuk manual bisa lewat terminal dengan command "sudo nano /etc/hosts"
