### ISSUE TITLE
bug dan request

### ISSUE THREAD

**Issue by shirojishi** [apkcube/blockhostid#19]
ada bug di dengan site
-kissmanga.com
-kissanime.ru
stuck di please waiting 5 second ~ test site pake vpn masih work sitenya

request
-raw.senmanga.com

**Comment by apkcube** [comment]
Kemungkinan sitenya down. Barusan cek emang lagi down, mungkin kalo udah up nanti bisa lagi.

Kissmanga.com
http://www.isitdownrightnow.com/kissmanga.com.html
http://downforeveryoneorjustme.com/kissmanga.com

Kissanime.ru
http://www.isitdownrightnow.com/kissanime.ru.html
http://downforeveryoneorjustme.com/kissanime.ru

Untuk requestnya mungkin nanti, makan dulu gan laper :3

**Comment by apkcube** [comment]
Update request done.
Silahkan download versi terbaru

**Comment by shirojishi** [comment]
THANK YOU GAN
