### ISSUE TITLE
#ask

### ISSUE THREAD

**Issue by freoz** [apkcube/blockhostid#20]
cara dapetin itu ip host gimana ya bang?
misal hentaimama.com

**Comment by apkcube** [comment]
Silahkan cari IP Lookup, banyak tersedia website-website untuk mencari ip-nya disana.

**Comment by apkcube** [comment]
Apakah anda request website tersebut agar ditambahkan?

**Comment by freoz** [comment]
tentu, tolong ditambahkan. thanks sir

**Comment by apkcube** [comment]
Site telah ditambahkan.
