### ISSUE TITLE
Request new sites

### ISSUE THREAD

**Issue by Bagus23** [apkcube/blockhostid#29]
Request :
Bangbros.com
Blacked.com
Vixen.com
Throated.com
Lubed.com
Tushy.com
Tiny4k.com
X-art.com
Nubilefilms.com
FamilyStrokes.com
EvilAngel.com
Hardx.com
Girlsdoporn.com
Brattysis.com
Javjunkies.com
S1s1s1.com
Moodyz.com
Ideapocket.com
Oppai-av.com
Wanz-factory.com
Mutekimuteki.com
Prestige-av.com
Av-e-body.com
Gravuregirlz.com
Minimum-av.com
Dewamovie.tv
Data18.com
Mangago.me
Wetmelon.com
Javhd.pro
Scanlover.com
2chan.net
Javsubtitle.co
Asiansexdiary.com
Streetmeatasia.com
Asianstreetmeat.com
Yespornplease.com
Thiendia.com
Pornleech.com
Sexix.net
Chaturbate.com
Digitalplayground.com

**Comment by apkcube** [comment]
Ok ditunggu ya gan, mungkin besok baru saya kerjakan, sekalian mau nambah javhihi.com nih.

**Comment by apkcube** [comment]
Data sudah kami kumpulkan, tinggal menunggu waktu untuk rilis v20, ditunggu ya :)

[raw-request.txt](https://github.com/apkcube/blockhostid/files/1329062/raw-request.txt)

**Comment by apkcube** [comment]
Done, silahkan update..

Commit: https://github.com/apkcube/blockhostid/commit/06aabf2b6ccd985fc1122a90ff1f3486e0bb12e4
