### ISSUE TITLE
nhentai and chan.sankaku

### ISSUE THREAD

**Issue by lwiwensky1** [apkcube/blockhostid#7]
i can bypass the internet positif, but the image didnt shown up, all the image shown is broken image
![nhentai](https://user-images.githubusercontent.com/29788699/27718545-c7297d16-5d76-11e7-98f8-14bd60100c62.png)
![fireshot capture 9 - izumi sagiri i sankaku channel - anime man_ - https___chan sankakucomplex com_](https://user-images.githubusercontent.com/29788699/27718576-f3413380-5d76-11e7-8463-48ce744ab4c3.png)

**Comment by apkcube** [comment]
Fixed both, thx for reporting the bugs
