### ISSUE TITLE
request and bug

### ISSUE THREAD

**Issue by lwiwensky1** [apkcube/blockhostid#9]
please add http://www.tsumino.com/Books
and then nhentai.net is fine until we open the doujin page
it will become like this 
![image](https://user-images.githubusercontent.com/29788699/27801144-a4346f96-6046-11e7-92fa-c09132472d0c.png)
and https://chan.sankakucomplex.com is fine until we open the picture, it will become like this 
![image](https://user-images.githubusercontent.com/29788699/27801226-129e6b94-6047-11e7-9959-662ff76b8283.png)

thank you so much

**Comment by apkcube** [comment]
Ok, wait...

**Comment by apkcube** [comment]
Site added but we still dunno what happen with the bug, ill find the solution and fix it asap. thx.
